[package]
version = "0.1.0"
name = "negotiate-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
serde = "1.0.215"
sp1-zkvm = "3.4.0"
# fibonacci-lib = { path = "../lib" }
