[package]
name = "negotiate_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
serde = "1.0.215"
negotiate={path = "../../../negotiate"}
